# Generated by Django 4.2.4 on 2023-11-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Album',
        ),
    ]
